spring:
  application:
    name: SpringbootDockerElkKubernetDevProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springbootrealtimeendtoend
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081    
logging:
  file:
    name: C:/Users/Welcome/OneDrive/Desktop/logs/SpringbootDockerElkKubernetProject.log
management:
  tracing:
    sampling:
      probability: 1.0